<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // pg_trgm is provisioning, not schema: creating it needs privileges the
        // application role has no business holding in production. Assert it is
        // there and say exactly what to run if it is not — a clear instruction
        // beats a bare permission denial from three statements further down.
        $hasTrgm = DB::selectOne("SELECT 1 FROM pg_extension WHERE extname = 'pg_trgm'");

        if (! $hasTrgm) {
            throw new RuntimeException(
                'pg_trgm is required and is not installed on database '
                .DB::connection()->getDatabaseName()
                .'. Run as a superuser: CREATE EXTENSION pg_trgm; See docs/provisioning.md.'
            );
        }

        // ------------------------------------------------------------------
        // patients
        // ------------------------------------------------------------------
        Schema::create('patients', function (Blueprint $table) {
            $table->id();

            // Human-readable display identifier: MDR-004127-36
            // Generated by App\Registry\RegistryNumber. Never used as a foreign key.
            $table->string('registry_no', 20)->unique();

            $table->string('family_name', 80);
            $table->string('given_name', 80);
            $table->string('other_names', 120)->nullable();

            // Lowercased, punctuation-stripped, token-sorted. Written by the application on
            // save. Token sorting matters: "Kwame Mensah" and "Mensah Kwame" are the same
            // person recorded by two different clerks.
            $table->string('name_normalised', 200);

            $table->date('date_of_birth')->nullable();
            $table->boolean('dob_estimated')->default(false);
            $table->string('sex', 12);                       // male | female | other | unknown

            $table->string('phone_primary', 24)->nullable();
            $table->string('phone_alt', 24)->nullable();
            $table->string('contact_name', 120)->nullable();
            $table->string('contact_relationship', 60)->nullable();

            $table->string('residence_region', 60)->nullable();
            $table->string('residence_district', 60)->nullable();
            $table->string('residence_type', 12)->nullable(); // urban | rural

            // Lifecycle, not soft deletes. A patient record is never deleted.
            $table->string('status', 16)->default('active'); // active | deceased | withdrawn | transferred | merged
            $table->date('date_last_seen')->nullable();

            // Duplicates will happen. Merging must preserve both records.
            $table->foreignId('merged_into_id')->nullable()->constrained('patients')->nullOnDelete();
            $table->timestampTz('merged_at')->nullable();

            $table->timestampTz('enrolled_at');
            $table->foreignId('enrolled_by')->nullable()->constrained('users')->restrictOnDelete();

            // Client-generated UUID, supplied when a registration is created offline.
            // Makes POST /api/patients idempotent: a retry after a dropped connection
            // updates rather than creating a second patient.
            $table->uuid('client_ref')->nullable()->unique();

            // Audit of the duplicate check performed at registration.
            $table->jsonb('duplicate_check')->nullable();

            $table->timestamps();

            $table->index(['status', 'date_last_seen']);
            $table->index('family_name');
        });

        DB::statement("
            ALTER TABLE patients ADD CONSTRAINT patients_status_check
            CHECK (status IN ('active','deceased','withdrawn','transferred','merged'))
        ");

        DB::statement("
            ALTER TABLE patients ADD CONSTRAINT patients_sex_check
            CHECK (sex IN ('male','female','other','unknown'))
        ");

        // Trigram index: fuzzy name search and duplicate detection.
        DB::statement('CREATE INDEX patients_name_trgm ON patients USING GIN (name_normalised gin_trgm_ops)');

        // A merged record must point somewhere; an unmerged one must not.
        DB::statement("
            ALTER TABLE patients ADD CONSTRAINT patients_merge_consistency
            CHECK (
                (status = 'merged' AND merged_into_id IS NOT NULL)
                OR (status <> 'merged' AND merged_into_id IS NULL)
            )
        ");

        // ------------------------------------------------------------------
        // patient_identifiers — modelled on FHIR Patient.identifier
        //
        // Identifiers are rows, not columns. A patient may carry a hospital folder
        // number, an NHIS membership number, a Ghana Card PIN, an identifier from the
        // facility HIMS, and folder numbers from referring hospitals. Adding another
        // kind must never require a migration.
        //
        // Deliberately NOT globally unique: folder numbers are recycled, duplicated
        // across facilities and frequently mis-transcribed. The only uniqueness is
        // (patient_id, system, value), enforced below — see the spec.
        // ------------------------------------------------------------------
        Schema::create('patient_identifiers', function (Blueprint $table) {
            $table->id();
            $table->foreignId('patient_id')->constrained()->cascadeOnDelete();

            // Short code mapped to a FHIR system URI in config/identifiers.php:
            // folder | nhis | ghana_card | lhims | referral_folder | other
            $table->string('system', 32);
            $table->string('value', 64);
            $table->string('assigner', 120)->nullable();  // facility that issued it
            $table->boolean('is_primary')->default(false);
            $table->date('verified_on')->nullable();
            $table->string('verified_by_method', 40)->nullable(); // card seen | patient report | HIMS lookup
            $table->timestamps();

            $table->unique(['patient_id', 'system', 'value'], 'patient_identifiers_unique_per_patient');
            $table->index(['system', 'value']);
        });

        // One primary identifier per patient at most.
        DB::statement('
            CREATE UNIQUE INDEX patient_identifiers_one_primary
            ON patient_identifiers (patient_id)
            WHERE is_primary
        ');

        // ------------------------------------------------------------------
        // visits — minimal, enough for the dashboard. Extended in a later slice.
        // ------------------------------------------------------------------
        Schema::create('visits', function (Blueprint $table) {
            $table->id();
            $table->foreignId('patient_id')->constrained()->restrictOnDelete();
            $table->string('type', 24);                     // baseline | routine | unscheduled | telephone | data_only
            $table->date('scheduled_for')->nullable();
            $table->timestampTz('arrived_at')->nullable();
            $table->timestampTz('started_at')->nullable();
            $table->timestampTz('completed_at')->nullable();
            $table->foreignId('clinician_id')->nullable()->constrained('users')->nullOnDelete();
            $table->string('status', 16)->default('scheduled'); // scheduled | arrived | in_progress | complete | missed | cancelled
            $table->timestamps();

            $table->index(['scheduled_for', 'status']);
            $table->index(['clinician_id', 'completed_at']);
            $table->index(['patient_id', 'completed_at']);
        });

        DB::statement("
            ALTER TABLE visits ADD CONSTRAINT visits_status_check
            CHECK (status IN ('scheduled','arrived','in_progress','complete','missed','cancelled'))
        ");

        // ------------------------------------------------------------------
        // registry_sequence — the source of registry numbers.
        // A dedicated sequence, so numbers are never derived from patients.id
        // (which would leak enrolment order into the display ID and break after
        // any merge or deletion).
        // ------------------------------------------------------------------
        DB::statement('CREATE SEQUENCE IF NOT EXISTS registry_no_seq START 1 INCREMENT 1');

        // Tie the sequence's lifetime to the table it serves. A standalone
        // sequence survives a DROP TABLE — which leaves a wiped test database
        // holding a sequence the migration then cannot recreate.
        DB::statement('ALTER SEQUENCE registry_no_seq OWNED BY patients.id');
    }

    public function down(): void
    {
        DB::statement('DROP SEQUENCE IF EXISTS registry_no_seq');
        Schema::dropIfExists('visits');
        Schema::dropIfExists('patient_identifiers');
        Schema::dropIfExists('patients');
    }
};
